#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=rk2818
MANUFACTURER=rockchip

mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/app/TSCalibration.apk ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/TSCalibration.apk
adb pull /system/etc/firmware/DspBoot.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/DspBoot.rkl
adb pull /system/etc/firmware/DspOs.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/DspOs.rkl
adb pull /system/etc/firmware/rk28_flv1.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk28_flv1.rkl
adb pull /system/etc/firmware/rk28_h263enc.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk28_h263enc.rkl
adb pull /system/etc/firmware/rk28_h263.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk28_h263.rkl
adb pull /system/etc/firmware/rk28_h264_db.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk28_h264_db.rkl
adb pull /system/etc/firmware/rk28_h264.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk28_h264.rkl
adb pull /system/etc/firmware/rk28_jpegenc.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk28_jpegenc.rkl
adb pull /system/etc/firmware/rk28_jpeg.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk28_jpeg.rkl
adb pull /system/etc/firmware/rk28_mp4v.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk28_mp4v.rkl
adb pull /system/etc/firmware/rk28_mpeg2.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk28_mpeg2.rkl
adb pull /system/etc/firmware/rk28_rv30.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk28_rv30.rkl
adb pull /system/etc/firmware/rk28_rv40.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk28_rv40.rkl
adb pull /system/etc/firmware/rk28_test.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk28_test.rkl
adb pull /system/etc/firmware/rk28_wmv.rkl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rk28_wmv.rkl
adb pull /system/etc/firmware/rkl.ver ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rkl.ver
adb pull /system/etc/firmware/sd8686.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/sd8686.bin
adb pull /system/etc/firmware/sd8686_helper.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/sd8686_helper.bin
adb pull /system/lib/hw/copybit.rk28board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/copybit.rk28board.so
adb pull /system/lib/hw/gralloc.rk28board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/gralloc.rk28board.so
adb pull /system/lib/hw/lights.rk28board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/lights.rk28board.so
adb pull /system/lib/hw/overlay.rk28board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/overlay.rk28board.so
adb pull /system/lib/hw/sensors.rk28board.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/sensors.rk28board.so
adb pull /system/lib/libcamera.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libcamera.so
adb pull /system/lib/modules/wlan.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wlan.ko


(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libcamera.so:obj/lib/libcamera.so

# All the blobs necessary for rk2818
PRODUCT_COPY_FILES += \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/TSCalibration.apk:system/app/TSCalibration.apk \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/DspBoot.rkl:system/etc/firmware/DspBoot.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/DspOs.rkl:system/etc/firmware/DspOs.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk28_flv1.rkl:system/etc/firmware/rk28_flv1.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk28_h263enc.rkl:system/etc/firmware/rk28_h263enc.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk28_h263.rkl:system/etc/firmware/rk28_h263.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk28_h264_db.rkl:system/etc/firmware/rk28_h264_db.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk28_h264.rkl:system/etc/firmware/rk28_h264.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk28_jpegenc.rkl:system/etc/firmware/rk28_jpegenc.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk28_jpeg.rkl:system/etc/firmware/rk28_jpeg.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk28_mp4v.rkl:system/etc/firmware/rk28_mp4v.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk28_mpeg2.rkl:system/etc/firmware/rk28_mpeg2.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk28_rv30.rkl:system/etc/firmware/rk28_rv30.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk28_rv40.rkl:system/etc/firmware/rk28_rv40.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk28_test.rkl:system/etc/firmware/rk28_test.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rk28_wmv.rkl:system/etc/firmware/rk28_wmv.rkl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rkl.ver:system/etc/firmware/rkl.ver \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/sd8686.bin:system/etc/firmware/sd8686.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/sd8686_helper.bin:system/etc/firmware/sd8686_helper.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/copybit.rk28board.so:system/lib/hw/copybit.rk28board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gralloc.rk28board.so:system/lib/hw/gralloc.rk28board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/lights.rk28board.so:system/lib/hw/lights.rk28board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/overlay.rk28board.so:system/lib/hw/overlay.rk28board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/sensors.rk28board.so:system/lib/hw/sensors.rk28board.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libcamera.so:system/lib/libcamera.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wlan.ko:system/lib/modules/wlan.ko \\
EOF

./setup-makefiles.sh
