#!/system/bin/sh

if [ -f /data/misc/pointercal ]; then
	set -- `cat /data/misc/pointercal`

	for i in /sys/class/input/input*/capabilities/abs; do
		if [ "`cat $i`" = "0" ]; then
			continue
		fi
		name=`cat ${i%%capabilities/abs}name`
		echo touch.pointercal.x1=$1 > "/data/misc/idc/$name.idc"
		echo touch.pointercal.x2=$2 >> "/data/misc/idc/$name.idc"
		echo touch.pointercal.x3=$3 >> "/data/misc/idc/$name.idc"
		echo touch.pointercal.y1=$4 >> "/data/misc/idc/$name.idc"
		echo touch.pointercal.y2=$5 >> "/data/misc/idc/$name.idc"
		echo touch.pointercal.y3=$6 >> "/data/misc/idc/$name.idc"
		echo touch.pointercal.scale=$7 >> "/data/misc/idc/$name.idc"
	done
fi
